name: thesis
dependencies:
- apptools=4.2.1=py27_0
- binstar=0.10.1=py27_1
- cairo=1.12.2=2
- clyent=0.3.2=py27_0
- configobj=5.0.6=py27_0
- dateutil=2.1=py27_2
- envisage=4.4.0=py27_1
- freetype=2.4.10=0
- h5py=2.4.0=np19py27_0
- hdf5=1.8.14=0
- ipython=3.1.0=py27_0
- ipython-notebook=2.3.0=py27_0
- jinja2=2.7.3=py27_1
- jpeg=8d=0
- lcms=1.19=0
- libpng=1.5.13=1
- libsodium=0.4.5=0
- markupsafe=0.23=py27_0
- matplotlib=1.4.2=np19py27_0
- mayavi=4.3.1=np19py27_1
- nose=1.3.4=py27_1
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pandas=0.16.0=np19py27_1
- patsy=0.3.0=np19py27_0
- pil=1.1.7=py27_1
- pip=6.1.1=py27_0
- pixman=0.26.2=0
- progressbar=2.3=py27_0
- py2cairo=1.10.0=py27_1
- pyface=4.4.0=py27_0
- pyparsing=2.0.1=py27_0
- pyqt=4.10.4=py27_0
- python=2.7.9=2
- python-dateutil=2.4.2=py27_0
- pytz=2015.2=py27_0
- pyyaml=3.11=py27_0
- pyzmq=14.4.0=py27_0
- qt=4.8.5=0
- readline=6.2=2
- requests=2.5.1=py27_0
- scikit-image=0.10.1=np19py27_0
- scikit-learn=0.16.0=np19py27_0
- scipy=0.15.1=np19py27_0
- setuptools=15.0=py27_0
- sip=4.15.5=py27_0
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- ssl_match_hostname=3.4.0.2=py27_0
- statsmodels=0.6.1=np19py27_0
- system=5.8=2
- tk=8.5.18=0
- tornado=4.0.2=py27_0
- traits=4.4.0=py27_0
- traitsui=4.4.0=py27_0
- vtk=5.10.1=py27_1
- yaml=0.1.4=0
- zeromq=4.0.4=0
- zlib=1.2.8=0
- pip:
  - backports.ssl-match-hostname==3.4.0.2
  - click==4.0
  - docopt==0.6.1
  - easydev==0.8.3
  - flask==0.10.1
  - futures==2.2.0
  - gc-turbulence (/home/aaron/code/gc_turbulence)==0.1
  - greenlet==0.4.5
  - grip==3.0.0
  - hcs-utils==1.4
  - itsdangerous==0.24
  - jsonschema==2.4.0
  - labwaves (/home/aaron/code/labwaves)==0.1
  - markdown==2.4.1
  - msgpack-python==0.4.6
  - neovim==0.0.34
  - notedown (/home/aaron/code/notedown)==1.4.2
  - ordereddict==1.1
  - pandoc-attributes (/home/aaron/code/pandoc-attributes)==0.1.7
  - pandoc-internal-references (/home/aaron/code/pandoc-reference-filter)==0.5
  - pandocfilters==1.2.2
  - parallelprogress==0.1
  - path-and-address==1.0.0
  - pbr==0.10.0
  - pharminv==0.2.1
  - pygments==1.6
  - pyperclip==1.5.7
  - runipy==0.1.1
  - sparse-dmd (/home/aaron/code/sparse_dmd)==0.2
  - spectrum==0.6.0
  - stevedore==1.1.0
  - trollius==1.0.4
  - update-checker==0.6
  - virtualenv==1.11.6
  - virtualenv-clone==0.2.5
  - virtualenvwrapper==4.3.1
  - wavelets (/home/aaron/code/wavelets)==0.1
  - werkzeug==0.9.6
  - wheel==0.24.0
