---
title: On the Structure and Dynamics of Gravity Currents in Homogeneous and Two-Layer Fluids

author: 
    name: Aaron O'Leary
    email: eeaol@leeds.ac.uk

abstract: |
    Lab work is difficult.

declaration: |
    This is all my own work, etc. etc.

acknowledgements: Lots and lots of people.

copyright: me and the University

university:
    name: The University of Leeds
    url: http://www.leeds.ac.uk

department:
    name: School of Earth and Environment
    url: http://see.leeds.ac.uk

group:
    name: Institute of Climate and Atmospheric Science
    url: http://www.see.leeds.ac.uk/research/icas/

thesis_class: build/latex/Thesis
build: build
...
