---
title: A profoundly interesting title.
author: 
    name: Your name
    email: your@email.address
abstract: |
    This is the abstract: a nice concise plain text description
    of what is to come.

    It can be spread over multiple paragraphs.

declaration: |
    This is all my own work, etc. etc.

acknowledgements: Lots and lots of people.

copyright: me and the University
...
